### ISSUE TITLE
Support for videos.

### ISSUE THREAD

**Issue by viktorgardart** [bufferapp/buffer-ios-image-viewer#12]
Will you support videos in the future? :smiley:

**Comment by DreamingInBinary** [comment]
Good one - I'll think on this one and get back to you with a better answer :). 

If we do, I definitely want it to be as easy to use technically speaking like it is now 👍

**Comment by viktorgardart** [comment]
Awesome! 👌

**Comment by shusain93** [comment]
I needed this so I made a *really* bad fork. Code is glued together with glitter everywhere.

https://github.com/shusain93/buffer-ios-image-viewer

I also added some other features like a caption interface so you can have both a title and caption displayed alongside each photo.

To use my addons just point the cocoa pod at my repo and use `EEPhoto` instead of a string or URL or whatever. EEPhoto has a `url` and a `title`/`description` attribute which are read for creating the caption view. Set those to nil to disable the view.

Again, glued together. You've been warned.

**Comment by DreamingInBinary** [comment]
Thanks fro sharing @shusain93 - unfortunately we haven't had a business case for video support in this project as we use iOS' APIs to display video in Buffer. @viktorgardart maybe his fork might meet your needs!
